version: "2.0"

services:
  mongodb_adm_host:
    image: mongo:5.0
    container_name: mongodb_adm_host
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_DB_NAME}"
    ports:
      - 27017:27017
    volumes:
      - mongodb_adm_host:/data/db

  web_server:
    image: node:16.16.0
    container_name: web_server
    restart: always
    ports:
      - 8888:8888
    working_dir: /app
    volumes:
      - ./WebServer:/app
      - /app/node_modules
    command: sh -c "npm install && npm run start"

  web_admin:
    image: node:16.16.0
    container_name: web_admin
    restart: always
    ports:
      - 3000:3000
    build: ./WebAdmin
    working_dir: /app
    volumes:
      - ./WebAdmin:/app
      - /app/node_modules
    command: sh -c "npm install && npm run start"

  web_client:
    image: node:16.16.0
    container_name: web_client
    restart: always
    ports:
      - 3001:3001
    build: ./WebClient
    working_dir: /app
    volumes:
      - ./WebClient:/app
      - /app/node_modules
    command: sh -c "npm install && npm run start"

volumes:
  mongodb_adm_host:
    driver: local
